In [1]:
print("hi")

hi

In [6]:
import os
import numpy as np

In [3]:
with open ("인원조사.csv", "r") as f:
    print(f.read())

이름,키,몸무게,성별
홍일동,166,45,여
홍이동,168,60,남
홍삼동,170,50,여
홍사동,172,55,남
홍오동,174,78,남

In [7]:
import pandas as pd

In [9]:
pd.read_csv("./인원조사.csv")

    이름    키  몸무게 성별
0  홍일동  166   45  여
1  홍이동  168   60  남
2  홍삼동  170   50  여
3  홍사동  172   55  남
4  홍오동  174   78  남

In [10]:
import numpy as np

In [11]:
np.array([166, 168, 170, 172, 174])

array([166, 168, 170, 172, 174])

In [12]:
height=np.array([166, 168, 170, 172, 174])

In [13]:
weight=np.array([45, 60, 50, 55, 78])

In [14]:
sung=np.array(['여','남','여','남','남'])

In [18]:
pung= sum(height) / len(height)
print(pung)

170.0

In [19]:
np.average(height)

np.float64(170.0)

In [20]:
np.mean(height)

np.float64(170.0)

In [21]:
np.array([1,2,3]) + np.array([1,2,3])

array([2, 4, 6])

In [26]:
pyo= np.array(height) - np.mean(height)

In [31]:
pyo2= np.array(pyo) * np.array(pyo)

In [36]:
np.sum(pyo2) / len(height)

np.float64(8.0)

In [37]:
np.std(height)

np.float64(2.8284271247461903)

In [38]:
student_df=pd.read_csv("./인원조사.csv")

In [40]:
student_df["몸무게"]

0    45
1    60
2    50
3    55
4    78
Name: 몸무게, dtype: int64

In [41]:
student_df["키"].var()

np.float64(10.0)

In [42]:
student_df["키"].std()

np.float64(3.1622776601683795)

In [43]:
student_df.describe()

                키        몸무게
count    5.000000   5.000000
mean   170.000000  57.600000
std      3.162278  12.700394
min    166.000000  45.000000
25%    168.000000  50.000000
50%    170.000000  55.000000
75%    172.000000  60.000000
max    174.000000  78.000000

In [44]:
pd.read_csv("인원조사.csv")

    이름    키  몸무게 성별
0  홍일동  166   45  여
1  홍이동  168   60  남
2  홍삼동  170   50  여
3  홍사동  172   55  남
4  홍오동  174   78  남

In [45]:
student_df = pd.read_csv("인원조사.csv")

In [46]:
student_df.describe()

                키        몸무게
count    5.000000   5.000000
mean   170.000000  57.600000
std      3.162278  12.700394
min    166.000000  45.000000
25%    168.000000  50.000000
50%    170.000000  55.000000
75%    172.000000  60.000000
max    174.000000  78.000000

In [50]:
student_df["키"].std()

np.float64(3.1622776601683795)

In [51]:
mc_df= pd.read_csv("C:/ex/data/10_mct_tool - 복사.csv")

In [52]:
mc_df.describe()

             공구번호         사이클타임         온도         전류          회전수         토크
count        40.0     40.000000  40.000000  40.000000    40.000000   40.00000
mean   43000007.0  15012.025000  30.025000  23.582500  4212.625000   10.70000
std           0.0   3989.321351   0.619657  13.058943  1159.525471   31.83628
min    43000007.0   2149.000000  29.000000  14.980000    58.000000    1.00000
25%    43000007.0  15589.750000  30.000000  18.392500  4603.000000    2.00000
50%    43000007.0  15605.000000  30.000000  18.600000  4603.000000    2.00000
75%    43000007.0  15611.000000  30.000000  19.605000  4603.000000    3.00000
max    43000007.0  21213.000000  31.000000  64.480000  4987.000000  147.00000

In [53]:
mc_df["토크"].std()

np.float64(31.83627990121833)

In [54]:
mc_df["토크"]

0       2
1       2
2      21
3       2
4       3
5       2
6       2
7       3
8       2
9     147
10      3
11      2
12      2
13      3
14      2
15      3
16      3
17      2
18      2
19      2
20      5
21      3
22      3
23      1
24      2
25      2
26      1
27      3
28      2
29      3
30      2
31      2
32      9
33      2
34      3
35    146
36      2
37     21
38      3
39      3
Name: 토크, dtype: int64

In [55]:
mc_df.columns

Index(['공구번호', '사이클타임', '온도', '전류', '회전수', '토크'], dtype='str')

In [56]:
mc_df.values

array([[4.3000007e+07, 2.1156000e+04, 3.0000000e+01, 1.5440000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5611000e+04, 3.0000000e+01, 1.8690000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5633000e+04, 3.0000000e+01, 6.2480000e+01,
        4.9670000e+03, 2.1000000e+01],
       [4.3000007e+07, 1.5601000e+04, 3.0000000e+01, 1.8370000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5607000e+04, 2.9000000e+01, 1.8670000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5557000e+04, 3.0000000e+01, 1.4980000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5557000e+04, 3.1000000e+01, 1.8400000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5636000e+04, 3.1000000e+01, 6.2060000e+01,
        4.9870000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5600000e+04, 3.0000000e+01, 1.8550000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5634000e+04, 3.0000000e+01, 6.4480000e+01,
        3.6320000e+03, 1.4700000e+02],
       [4.3000007e+07, 2.1207000e+04, 3.0000000e+01, 1.8840000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5554000e+04, 3.0000000e+01, 2.4450000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5600000e+04, 3.0000000e+01, 1.8510000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5606000e+04, 3.0000000e+01, 1.9190000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5612000e+04, 2.9000000e+01, 1.8420000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5602000e+04, 3.0000000e+01, 1.8480000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5602000e+04, 3.1000000e+01, 1.9050000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5557000e+04, 3.1000000e+01, 1.8660000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5606000e+04, 3.0000000e+01, 1.8290000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 2.1490000e+03, 2.9000000e+01, 1.8650000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 2.1213000e+04, 3.0000000e+01, 2.1810000e+01,
        5.8000000e+01, 5.0000000e+00],
       [4.3000007e+07, 1.5601000e+04, 3.0000000e+01, 1.8450000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5606000e+04, 3.0000000e+01, 1.8470000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5611000e+04, 3.0000000e+01, 2.3740000e+01,
        1.2160000e+03, 1.0000000e+00],
       [4.3000007e+07, 1.5559000e+04, 2.9000000e+01, 1.5000000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5607000e+04, 3.0000000e+01, 1.8370000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5608000e+04, 3.1000000e+01, 1.7850000e+01,
        1.2170000e+03, 1.0000000e+00],
       [4.3000007e+07, 1.5602000e+04, 3.1000000e+01, 1.8970000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5557000e+04, 3.0000000e+01, 1.5710000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 2.1540000e+03, 2.9000000e+01, 1.9040000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5605000e+04, 3.0000000e+01, 1.8480000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5605000e+04, 3.0000000e+01, 1.8480000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5610000e+04, 3.0000000e+01, 3.6330000e+01,
        1.2410000e+03, 9.0000000e+00],
       [4.3000007e+07, 1.5600000e+04, 2.9000000e+01, 1.5030000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5607000e+04, 2.9000000e+01, 1.9170000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 1.5634000e+04, 3.0000000e+01, 4.6430000e+01,
        3.1430000e+03, 1.4600000e+02],
       [4.3000007e+07, 1.5558000e+04, 3.1000000e+01, 1.7090000e+01,
        4.6030000e+03, 2.0000000e+00],
       [4.3000007e+07, 1.5631000e+04, 3.1000000e+01, 4.0920000e+01,
        4.9670000e+03, 2.1000000e+01],
       [4.3000007e+07, 1.5603000e+04, 3.0000000e+01, 1.8450000e+01,
        4.6030000e+03, 3.0000000e+00],
       [4.3000007e+07, 2.2230000e+03, 3.0000000e+01, 2.0850000e+01,
        4.9870000e+03, 3.0000000e+00]])

In [57]:
mc_df.ndim

2

In [58]:
mc_df.describe

<bound method NDFrame.describe of         공구번호  사이클타임  온도     전류   회전수   토크
0   43000007  21156  30  15.44  4603    2
1   43000007  15611  30  18.69  4603    2
2   43000007  15633  30  62.48  4967   21
3   43000007  15601  30  18.37  4603    2
4   43000007  15607  29  18.67  4603    3
5   43000007  15557  30  14.98  4603    2
6   43000007  15557  31  18.40  4603    2
7   43000007  15636  31  62.06  4987    3
8   43000007  15600  30  18.55  4603    2
9   43000007  15634  30  64.48  3632  147
10  43000007  21207  30  18.84  4603    3
11  43000007  15554  30  24.45  4603    2
12  43000007  15600  30  18.51  4603    2
13  43000007  15606  30  19.19  4603    3
14  43000007  15612  29  18.42  4603    2
15  43000007  15602  30  18.48  4603    3
16  43000007  15602  31  19.05  4603    3
17  43000007  15557  31  18.66  4603    2
18  43000007  15606  30  18.29  4603    2
19  43000007   2149  29  18.65  4603    2
20  43000007  21213  30  21.81    58    5
21  43000007  15601  30  18.45  4603    3
22  43000007  15606  30  18.47  4603    3
23  43000007  15611  30  23.74  1216    1
24  43000007  15559  29  15.00  4603    2
25  43000007  15607  30  18.37  4603    2
26  43000007  15608  31  17.85  1217    1
27  43000007  15602  31  18.97  4603    3
28  43000007  15557  30  15.71  4603    2
29  43000007   2154  29  19.04  4603    3
30  43000007  15605  30  18.48  4603    2
31  43000007  15605  30  18.48  4603    2
32  43000007  15610  30  36.33  1241    9
33  43000007  15600  29  15.03  4603    2
34  43000007  15607  29  19.17  4603    3
35  43000007  15634  30  46.43  3143  146
36  43000007  15558  31  17.09  4603    2
37  43000007  15631  31  40.92  4967   21
38  43000007  15603  30  18.45  4603    3
39  43000007   2223  30  20.85  4987    3>

In [59]:
np.array([[1,2,3],[1,2,3]])

array([[1, 2, 3],
       [1, 2, 3]])

In [61]:
student_df.values[:,1:3]

array([[166, 45],
       [168, 60],
       [170, 50],
       [172, 55],
       [174, 78]], dtype=object)